//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iridio.Resources.WebSite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iridio.Resources.WebSite.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string AccountChangePasswordMenuTitle {
            get {
                return ResourceManager.GetString("AccountChangePasswordMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string AccountChangePasswordSuccessBackButton {
            get {
                return ResourceManager.GetString("AccountChangePasswordSuccessBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed succesfully.
        /// </summary>
        public static string AccountChangePasswordSuccessBody {
            get {
                return ResourceManager.GetString("AccountChangePasswordSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string AccountChangePasswordSuccessTitle {
            get {
                return ResourceManager.GetString("AccountChangePasswordSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string AccountChangePasswordTitle {
            get {
                return ResourceManager.GetString("AccountChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during login. Please correct and try again.
        /// </summary>
        public static string AccountLogOnError {
            get {
                return ResourceManager.GetString("AccountLogOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password?.
        /// </summary>
        public static string AccountLogOnRecoverPassword {
            get {
                return ResourceManager.GetString("AccountLogOnRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change.
        /// </summary>
        public static string AccountLogOnRecoverPasswordLink {
            get {
                return ResourceManager.GetString("AccountLogOnRecoverPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string AccountLogOnSubmit {
            get {
                return ResourceManager.GetString("AccountLogOnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Access.
        /// </summary>
        public static string AccountLogOnTitle {
            get {
                return ResourceManager.GetString("AccountLogOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate your email and press Return.&lt;br /&gt;An Email will be sent with indications.
        /// </summary>
        public static string AccountResetPasswordBody {
            get {
                return ResourceManager.GetString("AccountResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string AccountResetPasswordOK {
            get {
                return ResourceManager.GetString("AccountResetPasswordOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperate Password.
        /// </summary>
        public static string AccountResetPasswordTitle {
            get {
                return ResourceManager.GetString("AccountResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel user.
        /// </summary>
        public static string AccountUsersDeleteTitle {
            get {
                return ResourceManager.GetString("AccountUsersDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AccountUsersEditSubtitle {
            get {
                return ResourceManager.GetString("AccountUsersEditSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string AccountUsersEditTitle {
            get {
                return ResourceManager.GetString("AccountUsersEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users List.
        /// </summary>
        public static string AccountUsersIndexTitle {
            get {
                return ResourceManager.GetString("AccountUsersIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can change the password from the login page or from the profile.
        /// </summary>
        public static string AccountUsersPasswordNote {
            get {
                return ResourceManager.GetString("AccountUsersPasswordNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but an unexpected error occured while processing your request. Please try again later..
        /// </summary>
        public static string ErrorBody {
            get {
                return ResourceManager.GetString("ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language:.
        /// </summary>
        public static string LoginLanguageSelection {
            get {
                return ResourceManager.GetString("LoginLanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, page searched doesn&apos;t exist.
        /// </summary>
        public static string NotFoundBody {
            get {
                return ResourceManager.GetString("NotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ResetPasswordSuccessBackButton {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been sent an email with new password. Remember to change it via your profile.
        /// </summary>
        public static string ResetPasswordSuccessBody {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password completed.
        /// </summary>
        public static string ResetPasswordSuccessTitle {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessTitle", resourceCulture);
            }
        }
    }
}
